"use strict";

module.exports = [
  {   name: 'fighter A',
      slug: 'fighter_a',
      published: true,
      desc: 'the fighter A is the standard fighter of the kybons.',
      excerpt: 'this is the kybon standard fighter.',
      size: 2,
      class: 'fighter',
      category: 'common',
      cost: 1,
      fleet: 'kybon_hivefleet',
      slots: ['slot_1', 'slot_1', 'slot_1']
  },
  {   name: 'fighter B', 
      slug: 'fighter_b', 
      published: true, 
      desc: 'the fighter B is a fast kybon ship, usually striking fast and hiding before the enemy can retaliate.', 
      excerpt: 'the fastest kybon fighter.', 
      size: 2,
      class: 'fighter', 
      category: 'charge', 
      cost: 2,
      fleet: 'kybon_hivefleet',
      slots: ['slot_1', 'slot_2']
  },
  {   name: 'fighter C', 
      slug: 'fighter_c', 
      published: true, 
      desc: 'the fighter C is a bomber, capable of destroying ships twice its size.', 
      excerpt: 'a group of this bombers often is the last thing the unhappy crew of a frigate gets on their radar.',
      size: 2,
      class: 'fighter',
      category: 'heavy',
      cost: 3,
      fleet: 'kybon_hivefleet',
      slots: ['slot_1', 'slot_2']
  },
  {   name: 'hamdar',
      slug: 'hamdar',
      published: true,
      desc: 'the hamdar is a small well rounded fighter class ship capable of handling almost anything equally bad.',
      excerpt: 'the hamdar is a small well rounded fighter class ship.',
      size: 3,
      class: 'fighter',
      category: 'common',
      cost: 1,
      fleet: 'alterian_pirates',
      slots: ['slot_1', 'slot_1', 'slot_1']
  },
  {   name: 'tiamat', 
      slug: 'tiamat', 
      published: true, 
      desc: 'the tiamat is a fast but vulnerable ship capable of hitting and retreating in the same turn.', 
      excerpt: 'the tiamat is a fast but vulnerable ship.', 
      size: 3,
      class: 'fighter', 
      category: 'charge', 
      cost: 2,
      fleet: 'alterian_pirates',
      slots: ['slot_2', 'slot_1', 'slot_1']
  },
  {   name: 'polymesus', 
      slug: 'polymesus', 
      published: true, 
      desc: 'the polymesus was designed to strike surgically at vital points of the enemy ships.', 
      excerpt: 'polymesus is a small fighter class bomber.',
      size: 3,
      class: 'fighter', 
      category: 'heavy', 
      cost: 3,
      fleet: 'alterian_pirates',
      slots: ['slot_2', 'slot_1']
  },
  {   name: 'enratos', 
      slug: 'enratos', 
      published: true, 
      desc: 'the enratos is an elite frigate, capable of bombing big targets or attacking enemy fighters with the onboard cannons.', 
      excerpt: 'the enratos is an elite frigate', 
      size: 5,
      class: 'frigate', 
      category: 'elite', 
      cost: 10,
      fleet: 'alterian_pirates',
      slots: ['slot_2', 'slot_1', 'slot_1', 'slot_1']
  },
  {   name: 'calypso', 
      slug: 'calypso', 
      published: true, 
      desc: 'the calypso is a hq flagship, usually guarded by a fleet of enratos. it is the biggest fighter as of yet.', 
      excerpt: 'the calypso is a hq flagship.', 
      size: 5,
      class: 'frigate', 
      category: 'hq', 
      cost: 20,
      fleet: 'alterian_pirates',
      slots: ['slot_2', 'slot_2', 'slot_1', 'slot_1', 'slot_1', 'slot_1', 'slot_1']
  }
];
